# -*- coding: utf-8 -*-
"""mergedplot.up.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7cpncE8xsXGU6dyPVzkZUtBBzslEt34
"""

import pandas as pd
import glob
import os

# Step 1: Get all CSV files in the directory
file_list = glob.glob("*.csv")  # Adjust pattern if needed

# Step 2: Read all CSVs and store in a list
df_list = [pd.read_csv(file) for file in file_list]

# Step 3: Combine all DataFrames (assuming all have the "Strain" column already)
combined_df = pd.concat(df_list, ignore_index=True)

# Step 4: Keep only required columns
combined_df = combined_df[['Preferred_name', 'Pathway_name', 'FC', 'Strain']]

# Step 5: Save the merged file
combined_df.to_csv("merged_gene_pathways_with_strain.csv", index=False)

print("Merged data saved as 'merged_gene_pathways_with_strain.csv'")

combined_df.info()

with open("values.txt", "r") as file:
    values_to_remove = {line.strip() for line in file if line.strip()}
combined_df["Pathway_name"] = combined_df["Pathway_name"].str.strip()
annot_filtered= combined_df[~combined_df["Pathway_name"].isin(values_to_remove)]
print("Original shape:", combined_df.shape)        # (rows, columns)
print("Filtered shape:", annot_filtered.shape)

annot_filtered.dropna(subset=["Pathway_name", "Preferred_name"])
annot_filtered.info()

pathway_counts = annot_filtered.groupby("Pathway_name")["Preferred_name"].nunique()
# or .count() if duplicates are meaningful

# Sort descending
pathway_counts = pathway_counts.sort_values(ascending=False)
print(pathway_counts.head(10))

import matplotlib.pyplot as plt
import seaborn as sns
top10_counts = pathway_counts.head(20)
colors = sns.color_palette("Set2")
plt.figure(figsize=(8, 6))
sns.barplot(x=top10_counts.values, y=top10_counts.index, palette=colors)
plt.xlabel("Number of Genes")
plt.ylabel("Pathway")
plt.title("Top 20 Pathways: Colistin")
plt.tight_layout()
plt.savefig("Top20PathwaysbyGeneCountStrain.png", dpi=600, bbox_inches='tight')
plt.show()

# Count occurrences of each pathway per strain
pathway_counts = annot_filtered.groupby(["Strain", "Pathway_name"]).size().reset_index(name="Count")

# Sort by most common pathways
top_pathways = pathway_counts.groupby("Pathway_name")["Count"].sum().sort_values(ascending=False).head(20).index

# Filter to only the top 20 pathways
filtered_data = pathway_counts[pathway_counts["Pathway_name"].isin(top_pathways)]

# Pivot table for heatmap (Pathways vs Strains)
heatmap_data = filtered_data.pivot(index="Pathway_name", columns="Strain", values="Count").fillna(0)

plt.figure(figsize=(10, 8))
sns.heatmap(heatmap_data, cmap="Blues", annot=True, fmt=".0f", linewidths=0.5)
plt.xlabel("Strain")
plt.ylabel("Pathway")
plt.title("Top 20 Pathways Across Strains")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("Top20_Pathways_vs_Strain.png", dpi=600, bbox_inches="tight")
plt.show()

# Pivot so rows = Pathway, columns = Gene, values = FC
# If a pathway has multiple entries for the same gene, pick an aggfunc (e.g., mean)
heatmap_df = annot_filtered.pivot_table(
    index="Pathway_name",
    columns="Preferred_name",
    values="FC",
    aggfunc="mean"
)

# Fill missing with 0 or NaN
heatmap_df = heatmap_df.fillna(0)

plt.figure(figsize=(12, 8))
sns.heatmap(
    heatmap_df,
    cmap="YlOrRd",  # a mild yellow→red palette

)
plt.title("Pathway vs. Gene Heatmap (Fold Change)", fontsize=14)
plt.xlabel("Gene Symbol")
plt.ylabel("Pathway")
plt.tight_layout()
plt.savefig("heatmap_high_res.png", dpi=600, bbox_inches='tight')
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Pivot to get Pathway & Strain on rows, Genes on columns
heatmap_df = annot_filtered.pivot_table(
    index=["Pathway_name", "Strain"],  # Multi-index: Pathway & Strain
    columns="Preferred_name",  # Genes as columns
    values="FC",
    aggfunc="mean"  # Aggregate if needed
)

# Fill missing values with 0 or NaN
heatmap_df = heatmap_df.fillna(0)

# Plot heatmap
plt.figure(figsize=(14, 10))
sns.heatmap(
    heatmap_df,
    cmap="YlOrRd",
    linewidths=0.5
)

plt.title("Pathway-Strain vs. Gene Heatmap (Fold Change)", fontsize=14)
plt.xlabel("Gene Symbol")
plt.ylabel("Pathway & Strain")
plt.tight_layout()

# Save as high-resolution PNG
plt.savefig("pathway_strain_gene_heatmap.png", dpi=600, bbox_inches="tight")
plt.show()

reference_df = pd.read_csv("pathway.reference.csv")  # Replace with your actual file name
reference_df.rename(columns={"Sub. Classification. Pathway": "Pathway_name"}, inplace=True)
reference_df.head()

broad_pathway_mapped = annot_filtered.merge(reference_df, on="Pathway_name", how="left")

main_pathway_fc = broad_pathway_mapped.groupby("Main. Classification. Pathway")["FC"].mean().sort_values(ascending=False)
print(main_pathway_fc.head(20))

top10_fc = main_pathway_fc.head(20)

plt.figure(figsize=(8, 6))
sns.barplot(x=top10_fc.values, y=top10_fc.index, palette="Set2")
plt.xlabel("Mean Fold Change")
plt.ylabel("Pathway")
plt.title("Top 20 Pathways: Colistin (Main Classification)")
plt.tight_layout()
plt.savefig("top_pathways_main_vlassification1.png", dpi=300, bbox_inches='tight')
plt.show()

broad_pathway_mapped["GeneCount"] = (
    broad_pathway_mapped
    .groupby("Main. Classification. Pathway")["Preferred_name"]
    .transform("nunique")  # or "count" if duplicates are okay
)

# 1) Aggregate so that each pathway has a single row
df_agg = (
    broad_pathway_mapped
    .groupby("Main. Classification. Pathway", as_index=False)
    .agg({
        "GeneCount": "max",  # or "mean" or "min"—whatever makes sense for your data
        "FC": "mean",        # example of also aggregating FC
        # ... add other columns to aggregate if needed ...
    })
)

# 2) Sort by GeneCount, then pick top 10
df_top10 = df_agg.sort_values("GeneCount", ascending=False).head(20)
df_top10.head()

import matplotlib.pyplot as plt
import seaborn as sns



# 1) Numeric y positions for a horizontal lollipop
df_top10["ypos"] = df_top10.index

# 2) Create a colormap based on GeneCount
cmap = sns.color_palette("viridis", as_cmap=True)
norm = plt.Normalize(df_top10["GeneCount"].min(), df_top10["GeneCount"].max())
colors = [cmap(norm(gc)) for gc in df_top10["GeneCount"]]

fig, ax = plt.subplots(figsize=(10, 6))

# 3) Plot stems
ax.axvline(x=0, color="gray", linestyle="--", alpha=0.6)
ax.hlines(y=df_top10["ypos"], xmin=0, xmax=df_top10["FC"], color="teal", alpha=0.7)

# 4) Plot markers
ax.scatter(df_top10["FC"], df_top10["ypos"], color=colors, s=100, edgecolors="black", alpha=0.9)

# 5) Labeling
ax.set_xlabel("Fold Change (FC)")
ax.set_ylabel("Pathway")
ax.set_title("Top 20 Pathways: Colistin ")

# 6) Tick labels
ax.set_yticks(df_top10["ypos"])
ax.set_yticklabels(df_top10["Main. Classification. Pathway"])

# 7) Colorbar
sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
sm.set_array([])
cbar = fig.colorbar(sm, ax=ax, orientation="vertical")
cbar.set_label("Gene Count")

plt.tight_layout()
plt.savefig("loloplot_plot_main_classification.png", dpi=300, bbox_inches='tight')
plt.show()
import os

# Create folder if it doesn't exist
os.makedirs("results", exist_ok=True)

# Save to the folder
combined_df.to_csv("results/merged_gene_pathways_with_strain.csv", index=False)
top10_counts.to_csv("results/top20_pathways_by_gene_counts.csv", header=["GeneCount"])
heatmap_data.to_csv("results/heatmap_data_top20_strains.csv")
heatmap_df.to_csv("results/heatmap_df_high_res.csv")
heatmap_df.to_csv("results/heatmap_df_pathway_strain_gene.csv")
top10_fc.to_csv("results/top20_pathways_by_fc_main_classification.csv", header=["MeanFC"])
df_top10.to_csv("results/top20_pathways_by_gene_count_main_classification.csv")
